server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/avanzapp}
    username: ${SPRING_DATASOURCE_USERNAME:avanzauser}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

app:
  storage:
    pdf-dir: ./storage/pdfs

