-- Limpia y recrea el esquema público para garantizar un estado conocido
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public AUTHORIZATION pg_database_owner;
GRANT ALL ON SCHEMA public TO pg_database_owner;
GRANT ALL ON SCHEMA public TO public;

SET search_path TO public;

-- Tabla de usuarios base para las demás relaciones
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    nombre VARCHAR(255),
    "password" VARCHAR(255),
    rol VARCHAR(255),
    actividad_economica VARCHAR(255),
    apellido VARCHAR(255),
    ciudad VARCHAR(255),
    departamento VARCHAR(255),
    direccion VARCHAR(255),
    documento VARCHAR(255),
    estado BOOLEAN,
    fecha_nacimiento TIMESTAMP(6),
    fecha_registro DATE,
    nombre_empresa VARCHAR(255),
    pais VARCHAR(255),
    ruc_empresa VARCHAR(255),
    telefono VARCHAR(255),
    tipo_cliente VARCHAR(255),
    ubicacion VARCHAR(255),
    ultima_sesion TIMESTAMP(6),
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.dnit_compra_cabecera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afectacion_exento VARCHAR(150),
    afectacion_grav10 VARCHAR(150),
    afectacion_grav5 VARCHAR(150),
    base_imponible NUMERIC(18, 2),
    condicion_operacion VARCHAR(20),
    exenta NUMERIC(18, 2),
    fecha_emision DATE,
    gravada_10 NUMERIC(18, 2),
    gravada_5 NUMERIC(18, 2),
    iva_10 NUMERIC(18, 2),
    iva_5 NUMERIC(18, 2),
    nro_comprobante VARCHAR(60),
    periodo_anio INT,
    periodo_emision VARCHAR(7),
    periodo_mes INT,
    proveedor_nombre VARCHAR(200),
    proveedor_ruc VARCHAR(25),
    tipo_comprobante VARCHAR(20),
    total_comprobante NUMERIC(18, 2),
    usuario_id BIGINT NOT NULL,
    CONSTRAINT uk_cabecera_usuario_periodo_nro UNIQUE (usuario_id, periodo_mes, periodo_anio, nro_comprobante),
    CONSTRAINT fk_cabecera_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE TABLE IF NOT EXISTS public.dnit_compra_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base NUMERIC(18, 2),
    clasificacion VARCHAR(150),
    exento NUMERIC(18, 2),
    iva NUMERIC(18, 2),
    tasa INT,
    tipo_linea VARCHAR(10) NOT NULL,
    cabecera_id BIGINT NOT NULL,
    CONSTRAINT uk_detalle_por_tipo UNIQUE (cabecera_id, tipo_linea),
    CONSTRAINT ck_detalle_tipo_linea CHECK (
        tipo_linea IN ('IVA10', 'IVA5', 'EXENTA')
    ),
    CONSTRAINT fk_detalle_cabecera FOREIGN KEY (cabecera_id) REFERENCES public.dnit_compra_cabecera(id)
);

CREATE TABLE IF NOT EXISTS public.dnit_ventas_cabecera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    numero_comprobante VARCHAR(60) NOT NULL,
    cliente_nombre VARCHAR(200),
    cliente_ruc VARCHAR(25),
    dia INT,
    fecha_emision DATE,
    periodo_emision VARCHAR(7),
    periodo_mes INT,
    periodo_anio INT,
    gravada_10 NUMERIC(18, 2),
    gravada_5 NUMERIC(18, 2),
    iva_10 NUMERIC(18, 2),
    iva_5 NUMERIC(18, 2),
    exenta NUMERIC(18, 2),
    total_comprobante NUMERIC(18, 2),
    retenciones NUMERIC(18, 2),
    afectacion_exento VARCHAR(150),
    afectacion_grav10 VARCHAR(150),
    afectacion_grav5 VARCHAR(150),
    CONSTRAINT uk_dnit_ventas_usuario_periodo_numero UNIQUE (usuario_id, periodo_mes, periodo_anio, numero_comprobante),
    CONSTRAINT fk_dnit_ventas_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE TABLE IF NOT EXISTS public.dnit_ventas_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cabecera_id BIGINT NOT NULL,
    tipo_linea VARCHAR(10) NOT NULL,
    tasa INT,
    base NUMERIC(18, 2),
    iva NUMERIC(18, 2),
    exento NUMERIC(18, 2),
    clasificacion VARCHAR(150),
    CONSTRAINT uk_dnit_ventas_detalle_tipo UNIQUE (cabecera_id, tipo_linea),
    CONSTRAINT fk_dnit_ventas_detalle_cabecera FOREIGN KEY (cabecera_id) REFERENCES public.dnit_ventas_cabecera(id)
);
